#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  sidebar: source/_data/sidebar.njk
  footer: source/_data/footer.njk
  variable: source/_data/variables.styl
  style: source/_data/styles.styl


# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

footer:
  since: 2014
  icon:
    name: fa fa-heart
    animated: true
    color: "#808080"
  copyright: NexT
  powered: false

creative_commons:
  license: by-nc-sa
  sidebar: true


# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

#scheme: Muse
#scheme: Mist
#scheme: Pisces
scheme: Gemini

darkmode: true


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-bell

  Docs:
    default: /docs/ || fa fa-book

    Getting Started:
      default: /getting-started/ || fa fa-flag
      Installation: /installation.html || fa fa-download
      Deployment: /deployment.html || fa fa-upload
      Configuration: /configuration.html || fa fa-wrench
      Internationalization: /internationalization.html || fa fa-globe
      Update from 5.x: /update-from-v5.html || fa fa-retweet

    Theme Settings:
      default: /theme-settings/ || fa fa-star
      Footer: /footer.html || far fa-swatchbook
      Sidebar: /sidebar.html || fa fa-bars
      Posts: /posts.html || fa fa-paragraph
      Custom Pages: /custom-pages.html || far fa-edit
      Custom Files: /custom-files.html || fa fa-palette
      SEO: /seo.html || fa fa-external-link-square-alt
      Front Matter: /front-matter.html || fa fa-heading

    Third Party Services:
      default: /third-party-services/ || fa fa-puzzle-piece
      Math Equations: /math-equations.html || fa fa-square-root-alt
      Comment Systems: /comments.html || far fa-comment
      Statistics and Analytics: /statistics-and-analytics.html || fa fa-chart-pie
      Post Widgets: /post-widgets.html || fa fa-gift
      Search Services: /search-services.html || fa fa-search-plus
      Chat Services: /chat-services.html || fa fa-comments
      External Libraries: /external-libraries.html || fa fa-plug

    Tag Plugins:
      default: /tag-plugins/ || fa fa-rocket
      Button: /button.html || fa fa-cube
      Caniuse: /caniuse.html || fa fa-signal
      Group Pictures: /group-pictures.html || far fa-images
      Label: /label.html || fa fa-hat-wizard
      Link Grid: /link-grid.html || fa fa-grip-vertical
      Mermaid: /mermaid.html || fa fa-project-diagram
      Note: /note.html || fa fa-adjust
      PDF: /pdf.html || far fa-file-pdf
      Tabs: /tabs.html || fa fa-columns

    Advanced Settings: /advanced-settings.html || fa fa-cog
    Troubleshooting: /troubleshooting.html || fa fa-life-ring

  Plugins: /plugins/ || fa fa-flask
  archives: /archives/ || fa fa-archive
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: true


# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/logo.svg
  rounded: true

social:
  GitHub: https://github.com/next-theme || fab fa-github
  E-Mail: mailto:support@theme-next.org || fa fa-envelope
  RSS: /atom.xml || fa fa-rss
  Gitter: https://gitter.im/hexo-next || fab fa-gitter

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: true
  wrap: true


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  updated_at:
    enable: false

symbols_count_time:
  separated_meta: true
  item_text_post: true
  item_text_total: true

post_edit:
  enable: true
  url: https://github.com/next-theme/theme-next-docs/edit/master/source/


# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: default
    dark: tomorrow-night
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: true
  permalink: https://github.com/next-theme/hexo-theme-next
  title: Fork NexT on GitHub


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: true

google_site_verification: 5AUIVYTbHIAuz-eQtxSfZbWW5eg9_EVZMSQycIuXrG0


# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

math:
  per_page: true
  mathjax:
    enable: true

pjax: true

mediumzoom: true


# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: true

disqus:
  enable: true
  shortname: theme-next
  count: true


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

motion:
  enable: true

vendors:
  anime: //cdn.jsdelivr.net/npm/animejs@3/lib/anime.min.js
  fontawesome: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css
